### ISSUE TITLE
MPD does not stop when switching to custom inputs.

### ISSUE THREAD

**Issue by Ghuru42** [PeteManchester/MediaPlayer#42]
* Using latest beta verison.

Got a CustomInput defined as this
`
    <Source>
        <name>Toslink 1</name>
        <type>Analog</type>
        <GPIO_PIN>3</GPIO_PIN>
    </Source>
`
When selecting this from Kazoo the status field changes to the right input, but mpd is not stopped.
The stop/skip buttons in Kazoo also gets disabled, as they should, so to stop mpd the only way to get back is to select a new song from the playlist, this get's Kazoo back to playlist and I can push stop.

For Airplay this seam to be working since java is able to open the soundcard, so mpd must be stopped and have released the device.

**Comment by PeteManchester** [comment]
I just tested this with my beta version with Kazoo and Kinksy and for me it works.

Maybe it is related to your issue with the CustomInputSource plugin

2015-04-27 14:00:28,872 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Analog Source Selected, attempt to Stop Playback
2015-04-27 14:00:28,902 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: Home PC
2015-04-27 14:00:28,902 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: Home PC
2015-04-27 14:00:28,903 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Don't Clear StandbyPin
2015-04-27 14:00:28,903 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 5 Low
2015-04-27 14:00:28,904 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 7 Low
2015-04-27 14:00:28,905 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 8 Low
2015-04-27 14:00:28,905 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 9 Low
2015-04-27 14:00:28,906 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 7
2015-04-27 14:00:28,906 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source Take Pin: 7 High
2015-04-27 14:00:29,565 [Thread-0] DEBUG [org.rpi.mpdplayer.StatusMonitor] Status Changed From : Playing To: Stopped
2015-04-27 14:00:29,566 [Thread-0] DEBUG [org.rpi.mpdplayer.MPDPlayer] Status Changed: Stopped
2015-04-27 14:00:29,566 [Thread-0] DEBUG [org.rpi.player.PlayManager] EventStatusChanged: Stopped

**Comment by PeteManchester** [comment]
I just tested this with my beta version with Kazoo and Kinksy and for me it works.

Maybe it is related to your issue with the CustomInputSource plugin

2015-04-27 14:00:28,871 [Thread-4] DEBUG [org.rpi.providers.PrvProduct] Source Selected: Home PC
2015-04-27 14:00:28,872 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Analog Source Selected, attempt to Stop Playback
2015-04-27 14:00:28,902 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: Home PC
2015-04-27 14:00:28,902 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: Home PC
2015-04-27 14:00:28,903 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Don't Clear StandbyPin
2015-04-27 14:00:28,903 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 5 Low
2015-04-27 14:00:28,904 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 7 Low
2015-04-27 14:00:28,905 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 8 Low
2015-04-27 14:00:28,905 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 9 Low
2015-04-27 14:00:28,906 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 7
2015-04-27 14:00:28,906 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source Take Pin: 7 High
2015-04-27 14:00:29,565 [Thread-0] DEBUG [org.rpi.mpdplayer.StatusMonitor] Status Changed From : Playing To: Stopped
2015-04-27 14:00:29,566 [Thread-0] DEBUG [org.rpi.mpdplayer.MPDPlayer] Status Changed: Stopped
2015-04-27 14:00:29,566 [Thread-0] DEBUG [org.rpi.player.PlayManager] EventStatusChanged: Stopped

**Comment by PeteManchester** [comment]
Do you have the CustomInputSource plugin installed (CustomInputSource.jar)?
https://github.com/PeteManchester/MediaPlayer/wiki/Plugins---Input-Selector

I don't see any reference to this in your log file

2015-04-27 12:57:15,616 [main] INFO [org.rpi.os.OSManager] Start of LoadPlugins
2015-04-27 12:57:15,792 [main] INFO [org.rpi.os.OSManager] End of LoadPlugnis

**Comment by Ghuru42** [comment]
Crap, I’m trying to do to many things at once….
No, I forgot to reinstall the plugin when updating to the latest beta.. My bad..

However, now that the plugin is there, I get a different error msg.

It’s always the first GPIO_PIN specified in the xml that gets this.
I’m using 0,2,3,7,12 and 13.
The pin,s work ok from the cmd line with the gpio utility.


—
2015-04-28 10:10:27,518 [main] DEBUG [org.rpi.os.Pi4JManager] Initialize Pi4J
2015-04-28 10:10:27,523 [Thread-4] DEBUG [org.rpi.utils.SecUtils] getInstancer
2015-04-28 10:10:27,582 [main] DEBUG [org.rpi.os.Pi4JManager] Initialized Pi4J
2015-04-28 10:10:27,583 [main] INFO  [org.rpi.plugin.input.InputSourcesImpl] Finished Configuring pi4j
2015-04-28 10:10:27,585 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] StandbyPIn: 2
2015-04-28 10:10:27,586 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Creating Default_Pin: 7
2015-04-28 10:10:27,607 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Creating Standby_Pin: 2
2015-04-28 10:10:27,611 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Creating Pins from Sources
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at net.xeoh.plugins.base.impl.spawning.Spawner.spawnPlugin(Spawner.java:204)
	at net.xeoh.plugins.base.impl.classpath.loader.AbstractLoader.processPending(AbstractLoader.java:251)
	at net.xeoh.plugins.base.impl.classpath.loader.AbstractLoader.tryToLoadClassAsPlugin(AbstractLoader.java:208)
	at net.xeoh.plugins.base.impl.classpath.loader.FileLoader.locateAllPluginsAt(FileLoader.java:138)
	at net.xeoh.plugins.base.impl.classpath.loader.FileLoader.loadFrom(FileLoader.java:105)
	at net.xeoh.plugins.base.impl.classpath.ClassPathManager.addFromLocation(ClassPathManager.java:140)
	at net.xeoh.plugins.base.impl.PluginManagerImpl.addPluginsFrom(PluginManagerImpl.java:127)
	at org.rpi.os.OSManager.loadPlugins(OSManager.java:258)
	at org.rpi.main.SimpleDevice.<init>(SimpleDevice.java:206)
	at org.rpi.main.StartMe.main(StartMe.java:95)
Caused by: java.lang.RuntimeException: Unable to open GPIO direction interface for pin [0]: No such file or directory

	at com.pi4j.wiringpi.GpioUtil.export(Native Method)
	at com.pi4j.io.gpio.RaspiGpioProvider.export(RaspiGpioProvider.java:69)
	at com.pi4j.io.gpio.impl.GpioPinImpl.export(GpioPinImpl.java:149)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionPin(GpioControllerImpl.java:520)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalOutputPin(GpioControllerImpl.java:645)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalOutputPin(GpioControllerImpl.java:672)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalOutputPin(GpioControllerImpl.java:684)
	at org.rpi.plugin.input.InputSourcesImpl.createPins(InputSourcesImpl.java:92)
	at org.rpi.plugin.input.InputSourcesImpl.<init>(InputSourcesImpl.java:43)
	... 14 more
java.lang.RuntimeException: Unable to open GPIO direction interface for pin [0]: No such file or directory

	at com.pi4j.wiringpi.GpioUtil.export(Native Method)
	at com.pi4j.io.gpio.RaspiGpioProvider.export(RaspiGpioProvider.java:69)
	at com.pi4j.io.gpio.impl.GpioPinImpl.export(GpioPinImpl.java:149)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionPin(GpioControllerImpl.java:520)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalOutputPin(GpioControllerImpl.java:645)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalOutputPin(GpioControllerImpl.java:672)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalOutputPin(GpioControllerImpl.java:684)
	at org.rpi.plugin.input.InputSourcesImpl.createPins(InputSourcesImpl.java:92)
	at org.rpi.plugin.input.InputSourcesImpl.<init>(InputSourcesImpl.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at net.xeoh.plugins.base.impl.spawning.Spawner.spawnPlugin(Spawner.java:204)
	at net.xeoh.plugins.base.impl.classpath.loader.AbstractLoader.processPending(AbstractLoader.java:251)
	at net.xeoh.plugins.base.impl.classpath.loader.AbstractLoader.tryToLoadClassAsPlugin(AbstractLoader.java:208)
	at net.xeoh.plugins.base.impl.classpath.loader.FileLoader.locateAllPluginsAt(FileLoader.java:138)
	at net.xeoh.plugins.base.impl.classpath.loader.FileLoader.loadFrom(FileLoader.java:105)
	at net.xeoh.plugins.base.impl.classpath.ClassPathManager.addFromLocation(ClassPathManager.java:140)
	at net.xeoh.plugins.base.impl.PluginManagerImpl.addPluginsFrom(PluginManagerImpl.java:127)
	at org.rpi.os.OSManager.loadPlugins(OSManager.java:258)
	at org.rpi.main.SimpleDevice.<init>(SimpleDevice.java:206)
	at org.rpi.main.StartMe.main(StartMe.java:95)
Apr 28, 2015 10:10:27 AM net.xeoh.plugins.base.impl.classpath.loader.AbstractLoader processPending
WARNING: Failed to spawn class  class org.rpi.plugin.input.InputSourcesImpl
2015-04-28 10:10:27,660 [main] INFO  [org.rpi.os.OSManager] End of LoadPlugnis
—

**Comment by PeteManchester** [comment]
I've not seen that one before, but a quick search found this similar problem, could it be the pin is being used by another app?
https://www.raspberrypi.org/forums/viewtopic.php?f=81&t=45143

**Comment by Ghuru42** [comment]
Well, yes and no.

The cmd line utility has no issues with accessing it, or, I don’t get any error msg back from it..
At the moment I have the cirrus board connected and they did not put a double header on it, instead they put a 2x10 header that is specified as 13  pins in the PDF.. So need to sort out what pin is what this afternoon and solder up another led array to my pins.

I just removed all ”gpio” rows from my InputSources.xml and now all works as expected, mpd is stopped.

**Comment by PeteManchester** [comment]
Yes, but if you read the detail on the forum they also had no problem with the gpio commands..

"I subsequently installed wiringPI itself, and have no problem running gpio commands."

Could it be that GPIO_PIN 0 is also used by I2C for your DAC?

**Comment by Ghuru42** [comment]
Well, no..

wireingpi pin 0 is gpio 17, that pin has no alternative function.
The same goes for 2 and 3, no alt functions.

i2c is on gpio02 and 03, thats 8 and 9 in wireingpi, not using those.
12,13 is the SPI port, that could be used..

Just getting around to sorting out how the cirrus board is wirered and soldering up a new led array, so will test with other pins as well, se what happens. Keep you posted.

**Comment by Ghuru42** [comment]
This does not make sense.. :-)

After going over the schematics for the Cirrus board I found that gpio 6,12,16 and 26 are untouched byt the board and exposed on an expansion header.
These are 22,26,27 and 25 in WireingPi numbers.
Running gpio on cmdline works fine, set the pin as output and toggle on/off and my leds work fine.

InputSources.xml is set as:
<?xml version="1.0" encoding="UTF-8"?>
<Sources>
    <Source>
        <name>PlayList</name>
        <type>Playlist</type>
	<GPIO_PIN>26</GPIO_PIN>
    </Source>

    <Source>
        <name>Toslink 1</name>
        <type>Analog</type>
	<GPIO_PIN>22</GPIO_PIN>
    </Source>

    <Source>
	<name>Songcast</name>
        <type>Receiver</type>
	<GPIO_PIN>27</GPIO_PIN>
    </Source>

    <Source>
	<name>AirPlay</name>
	<type>NetAux</type>
	<GPIO_PIN>25</GPIO_PIN>
    </Source>
</Sources>

Looking in the log:
2015-04-29 12:38:42,048 [main] INFO  [org.rpi.plugin.input.InputSourcesImpl] Finished Configuring pi4j
2015-04-29 12:38:42,050 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] StandbyPIn:
2015-04-29 12:38:42,051 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Default Pin was not Set
2015-04-29 12:38:42,051 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Standby Pin was not Set
2015-04-29 12:38:42,052 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Creating Pins from Sources
2015-04-29 12:38:42,053 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: Songcast
2015-04-29 12:38:42,054 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 27
2015-04-29 12:39:14,655 [Thread-21] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: PlayList
2015-04-29 12:39:14,656 [Thread-21] DEBUG [org.rpi.plugin.input.InputSourcesImpl] In Standby, do not update Sources
2015-04-29 12:39:14,664 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Standby: false
2015-04-29 12:39:24,321 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Analog Source Selected, attempt to Stop Playback
2015-04-29 12:39:24,343 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: Toslink 1
2015-04-29 12:39:24,343 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: Toslink 1
2015-04-29 12:39:24,343 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 22
2015-04-29 12:39:32,572 [Thread-21] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: PlayList
2015-04-29 12:39:32,572 [Thread-21] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: PlayList
2015-04-29 12:39:32,577 [Thread-21] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 26
All looks fine as far as I can see.

But, nothing happens on the LED,s.

So while mediaplayer is running and mpd is playing music I use the gpio cmdline, works fine, I can turn the led,s on and off.
But I do have to set the mode first..

Any suggestions?

/J

**Comment by PeteManchester** [comment]
Sorry, not many ideas on this one. someone had a problem with the CustomInput plugin last week, but again they had forgot to install the plugin, once they installed the plugin it worked..

One comamnd they did use to help diagnose the problem was 

gpio readall

Maybe you could also try to download the latest pi4j-core.jar and replace the existing library in  /home/pi/mediaplayer/mediaplayer_lib with the new version, then restart your pi.

Are you able to use any of the Pi4J samples?

http://pi4j.com/example/control.html

**Comment by Ghuru42** [comment]
I’m on to something, I think..

Installed the latest pi4j, after making sure that java and javac both point to jdk7.

The BlinkGpioExample as been adjusted to toggle 26/22 and use 27 as an input.
Compile the example as per instructions.
Works fine, the leds toggle as they should
—
root@gplayer:/opt/pi4j/examples# java -classpath .:classes:/opt/pi4j/lib/'*' BlinkGpioExample
<--Pi4J--> GPIO Blink Example ... started.
 ... the LED will continue blinking until the program is terminated.
 ... PRESS <CTRL-C> TO STOP THE PROGRAM.
^Croot@gplayer:/opt/pi4j/examples#
—

I then run the same example but point java to the mediaplayer_lib directory.
This does not work, runs but nothing happens.
root@gplayer:/opt/pi4j/examples# java -classpath .:classes:/opt/db/mediaplayer/mediaplayer_lib/'*' BlinkGpioExample
<--Pi4J--> GPIO Blink Example ... started.
 ... the LED will continue blinking until the program is terminated.
 ... PRESS <CTRL-C> TO STOP THE PROGRAM.
^Croot@gplayer:/opt/pi4j/examples#
root@gplayer:/opt/pi4j/examples#

So, I copy the lib/* to mediaplayer_lib/
And rerun the example above, now the example works.

I restart mediaplayer, but still no action on the LED.s.
I can run the example while mediaplayer is running without affecting audio or mediaplayer.

If I run gpio readall with mediaplayer on and change between my source and playlist, nothing changes.
I also notices that if I run the example and exit while on or two of the leds are active, they stay in that state when mediaplayer starts.

I also tried changing the run.sh to "java -classpath .:classes:/opt/db/mediaplayer/mediaplayer_lib/'*' -jar $SCRIPTPATH/mediaplayer.jar”
No difference..

Looking in the log file it all seams ”normal”
—
2015-04-30 10:21:49,713 [main] DEBUG [org.rpi.os.OSManager] Attempt to Load Plugin: CustomInputSource.jar file:/opt/db/mediaplayer/plugins/CustomInputSource.jar
2015-04-30 10:21:50,688 [main] INFO  [org.rpi.plugin.input.InputSourcesImpl] Finished Configuring pi4j
2015-04-30 10:21:50,689 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] StandbyPIn:
2015-04-30 10:21:50,689 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Default Pin was not Set
2015-04-30 10:21:50,690 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Standby Pin was not Set
2015-04-30 10:21:50,690 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Creating Pins from Sources
2015-04-30 10:21:50,691 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: Songcast
2015-04-30 10:21:50,691 [main] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 27
2015-04-30 10:22:12,311 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Analog Source Selected, attempt to Stop Playback
2015-04-30 10:22:12,312 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: Toslink 1
2015-04-30 10:22:12,312 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] In Standby, do not update Sources
2015-04-30 10:26:23,276 [Thread-3] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Standby: false
2015-04-30 10:26:23,285 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source Changed: PlayList
2015-04-30 10:26:23,285 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source ClearPins: PlayList
2015-04-30 10:26:23,286 [Thread-20] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 26
—
One thing that is off is that your log has more rows.
—
2015-04-27 14:00:28,903 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Don't Clear StandbyPin
2015-04-27 14:00:28,903 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 5 Low
2015-04-27 14:00:28,904 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 7 Low
2015-04-27 14:00:28,905 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 8 Low
2015-04-27 14:00:28,905 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Make Pin: 9 Low
2015-04-27 14:00:28,906 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Source PIN: 7
2015-04-27 14:00:28,906 [Thread-4] DEBUG [org.rpi.plugin.input.InputSourcesImpl] Changed Source Take Pin: 7 High
—
The ”Make Pin” rows are not present in my log files.. ?

/J

**Comment by PeteManchester** [comment]
Strange, that points towards the version of pi4J library distributed with MediaPlayer...
But someone got it working on a Pi2 last week..
I've upgraded to the latest version of pi4J, recompiled and create a beta distributed package which can be downloaded from 

https://github.com/PeteManchester/MediaPlayer/tree/master/com.upnp.mediaplayer/download/beta

You will need to save your config files, remove the mediaplayer directory, replace with new beta mediaplayer directory and then copy back your saved config files.

Let me know how that goes..

**Comment by Ghuru42** [comment]
With the latest Beta this is no longer an issue.
