### ISSUE TITLE
Crash on raspbian stretch 4.14.52-v7+ armv7l / java version "1.7.0_60"

### ISSUE THREAD

**Issue by rbg2024** [PeteManchester/MediaPlayer#75]
Hi,

after download of mediaplayer.zip from https://github.com/PeteManchester/MediaPlayer/releases to a Pi3 and unpacking the zip:

~/mediaplayer $ sudo ~/mediaplayer/run.sh
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/rpi/main/StartMe : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

is what I get.

Any ideas?

Thanks in advance

rbg2024

**Comment by rbg2024** [comment]
Hi, 

thanks for the quick reply. I‘d given the Java version in the Subj.    line. It‘s the Oracle JDK giving java -version 1.7.0_60 (instead of the _40 in your guide). 

Best regards,

rbg2024

**Comment by rbg2024** [comment]
PS: That‘s the default Oracle Java JDK currently installed on an up-to-date Raspbian stretch. 

Hi, 

thanks for the quick reply. I‘d given the Java version in the Subj.    line. It‘s the Oracle JDK giving java -version 1.7.0_60 (instead of the _40 in your guide). 

Best regards,

rbg2024

**Comment by PeteManchester** [comment]
Sorry I missed that, it was early in the morning.
The documentation is out of date now, the MediaPlayer requires at least Java 8, I will update the docs.

Let me know how it goes.

Thanks,

Pete.

**Comment by rbg2024** [comment]
Thanks, I‘ll try later this evening and report, but guess that‘s a downhill battle. 

Robert

**Comment by rbg2024** [comment]
Problem solved - thanks a lot!

**Comment by rbg2024** [comment]
Hi Pete,

thanks a lot, MediaPlayer is running fine! Is there a channel we could discuss feature questions?

Best regards,

Robert
